env:
  - TOXENV=flake8
  - TOXENV=py35-django20
  - TOXENV=py37-django20
  - TOXENV=py35-django21
  - TOXENV=py37-django21
  - TOXENV=py35-django22
  - TOXENV=py38-django22
  - TOXENV=py36-django30
  - TOXENV=py38-django30

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install codecov

install: pip install -U tox

script: tox -e ${TOXENV}

after_success:
  - codecov

deploy:
  provider: pypi
  user: sophilabs
  password:
    secure: SL52TviiKyBoJiQtAvywI3F6eJgngI0DNWa66ZZJroikTZXcp5zeO48bQCcT/g1H5dNfUsTBBc17jvE0tGu3F6WR8p9OAiHD1GIv9rn+kWJPkByHyrS5oCfmjFj81/N9F7FDwHcdt8Aide/Ik/OG8VaChE8jDKJuoA7hKumRSNg=
  on:
    condition: $TOXENV == py36-django30
    distributions: sdist bdist_wheel
    repo: sophilabs/django-qurl-templatetag
    tags: true
