sudo: false
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="2.2"
  - DJANGO="3.0"

before_install:
  - pip install codecov

install:
  - pip install -U tox-travis

script: tox

after_success:
  - codecov

deploy:
  provider: pypi
  user: sophilabs
  password:
    secure: SL52TviiKyBoJiQtAvywI3F6eJgngI0DNWa66ZZJroikTZXcp5zeO48bQCcT/g1H5dNfUsTBBc17jvE0tGu3F6WR8p9OAiHD1GIv9rn+kWJPkByHyrS5oCfmjFj81/N9F7FDwHcdt8Aide/Ik/OG8VaChE8jDKJuoA7hKumRSNg=
  on:
    condition: $TOXENV == py36-django30
    distributions: sdist bdist_wheel
    repo: sophilabs/django-qurl-templatetag
    tags: true
